/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { CuentaCorrienteService } from "../cuentaCorriente.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { CuentaCorrienteCreateInput } from "./CuentaCorrienteCreateInput";
import { CuentaCorriente } from "./CuentaCorriente";
import { CuentaCorrienteFindManyArgs } from "./CuentaCorrienteFindManyArgs";
import { CuentaCorrienteWhereUniqueInput } from "./CuentaCorrienteWhereUniqueInput";
import { CuentaCorrienteUpdateInput } from "./CuentaCorrienteUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class CuentaCorrienteControllerBase {
  constructor(
    protected readonly service: CuentaCorrienteService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: CuentaCorriente })
  @nestAccessControl.UseRoles({
    resource: "CuentaCorriente",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createCuentaCorriente(
    @common.Body() data: CuentaCorrienteCreateInput
  ): Promise<CuentaCorriente> {
    return await this.service.createCuentaCorriente({
      data: data,
      select: {
        createdAt: true,
        fechaVencimiento: true,
        folioFactura: true,
        id: true,
        monto: true,
        nombre: true,
        proveedor: true,
        run: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [CuentaCorriente] })
  @ApiNestedQuery(CuentaCorrienteFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "CuentaCorriente",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async cuentaCorrientes(
    @common.Req() request: Request
  ): Promise<CuentaCorriente[]> {
    const args = plainToClass(CuentaCorrienteFindManyArgs, request.query);
    return this.service.cuentaCorrientes({
      ...args,
      select: {
        createdAt: true,
        fechaVencimiento: true,
        folioFactura: true,
        id: true,
        monto: true,
        nombre: true,
        proveedor: true,
        run: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: CuentaCorriente })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CuentaCorriente",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async cuentaCorriente(
    @common.Param() params: CuentaCorrienteWhereUniqueInput
  ): Promise<CuentaCorriente | null> {
    const result = await this.service.cuentaCorriente({
      where: params,
      select: {
        createdAt: true,
        fechaVencimiento: true,
        folioFactura: true,
        id: true,
        monto: true,
        nombre: true,
        proveedor: true,
        run: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: CuentaCorriente })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CuentaCorriente",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateCuentaCorriente(
    @common.Param() params: CuentaCorrienteWhereUniqueInput,
    @common.Body() data: CuentaCorrienteUpdateInput
  ): Promise<CuentaCorriente | null> {
    try {
      return await this.service.updateCuentaCorriente({
        where: params,
        data: data,
        select: {
          createdAt: true,
          fechaVencimiento: true,
          folioFactura: true,
          id: true,
          monto: true,
          nombre: true,
          proveedor: true,
          run: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: CuentaCorriente })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CuentaCorriente",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteCuentaCorriente(
    @common.Param() params: CuentaCorrienteWhereUniqueInput
  ): Promise<CuentaCorriente | null> {
    try {
      return await this.service.deleteCuentaCorriente({
        where: params,
        select: {
          createdAt: true,
          fechaVencimiento: true,
          folioFactura: true,
          id: true,
          monto: true,
          nombre: true,
          proveedor: true,
          run: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
