/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { GastoService } from "../gasto.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { GastoCreateInput } from "./GastoCreateInput";
import { Gasto } from "./Gasto";
import { GastoFindManyArgs } from "./GastoFindManyArgs";
import { GastoWhereUniqueInput } from "./GastoWhereUniqueInput";
import { GastoUpdateInput } from "./GastoUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class GastoControllerBase {
  constructor(
    protected readonly service: GastoService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Gasto })
  @nestAccessControl.UseRoles({
    resource: "Gasto",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createGasto(@common.Body() data: GastoCreateInput): Promise<Gasto> {
    return await this.service.createGasto({
      data: data,
      select: {
        createdAt: true,
        descripcion: true,
        id: true,
        monto: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Gasto] })
  @ApiNestedQuery(GastoFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Gasto",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async gastos(@common.Req() request: Request): Promise<Gasto[]> {
    const args = plainToClass(GastoFindManyArgs, request.query);
    return this.service.gastos({
      ...args,
      select: {
        createdAt: true,
        descripcion: true,
        id: true,
        monto: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Gasto })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Gasto",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async gasto(
    @common.Param() params: GastoWhereUniqueInput
  ): Promise<Gasto | null> {
    const result = await this.service.gasto({
      where: params,
      select: {
        createdAt: true,
        descripcion: true,
        id: true,
        monto: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Gasto })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Gasto",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateGasto(
    @common.Param() params: GastoWhereUniqueInput,
    @common.Body() data: GastoUpdateInput
  ): Promise<Gasto | null> {
    try {
      return await this.service.updateGasto({
        where: params,
        data: data,
        select: {
          createdAt: true,
          descripcion: true,
          id: true,
          monto: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Gasto })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Gasto",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteGasto(
    @common.Param() params: GastoWhereUniqueInput
  ): Promise<Gasto | null> {
    try {
      return await this.service.deleteGasto({
        where: params,
        select: {
          createdAt: true,
          descripcion: true,
          id: true,
          monto: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
