/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { PagoFacturaService } from "../pagoFactura.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PagoFacturaCreateInput } from "./PagoFacturaCreateInput";
import { PagoFactura } from "./PagoFactura";
import { PagoFacturaFindManyArgs } from "./PagoFacturaFindManyArgs";
import { PagoFacturaWhereUniqueInput } from "./PagoFacturaWhereUniqueInput";
import { PagoFacturaUpdateInput } from "./PagoFacturaUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PagoFacturaControllerBase {
  constructor(
    protected readonly service: PagoFacturaService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: PagoFactura })
  @nestAccessControl.UseRoles({
    resource: "PagoFactura",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createPagoFactura(
    @common.Body() data: PagoFacturaCreateInput
  ): Promise<PagoFactura> {
    return await this.service.createPagoFactura({
      data: data,
      select: {
        createdAt: true,
        fechaVencimiento: true,
        folioFactura: true,
        id: true,
        montoFactura: true,
        montoPagado: true,
        nombreProveedor: true,
        notificacionVencida: true,
        pagado: true,
        runProveedor: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [PagoFactura] })
  @ApiNestedQuery(PagoFacturaFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "PagoFactura",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async pagoFacturas(@common.Req() request: Request): Promise<PagoFactura[]> {
    const args = plainToClass(PagoFacturaFindManyArgs, request.query);
    return this.service.pagoFacturas({
      ...args,
      select: {
        createdAt: true,
        fechaVencimiento: true,
        folioFactura: true,
        id: true,
        montoFactura: true,
        montoPagado: true,
        nombreProveedor: true,
        notificacionVencida: true,
        pagado: true,
        runProveedor: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: PagoFactura })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PagoFactura",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async pagoFactura(
    @common.Param() params: PagoFacturaWhereUniqueInput
  ): Promise<PagoFactura | null> {
    const result = await this.service.pagoFactura({
      where: params,
      select: {
        createdAt: true,
        fechaVencimiento: true,
        folioFactura: true,
        id: true,
        montoFactura: true,
        montoPagado: true,
        nombreProveedor: true,
        notificacionVencida: true,
        pagado: true,
        runProveedor: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: PagoFactura })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PagoFactura",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updatePagoFactura(
    @common.Param() params: PagoFacturaWhereUniqueInput,
    @common.Body() data: PagoFacturaUpdateInput
  ): Promise<PagoFactura | null> {
    try {
      return await this.service.updatePagoFactura({
        where: params,
        data: data,
        select: {
          createdAt: true,
          fechaVencimiento: true,
          folioFactura: true,
          id: true,
          montoFactura: true,
          montoPagado: true,
          nombreProveedor: true,
          notificacionVencida: true,
          pagado: true,
          runProveedor: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: PagoFactura })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PagoFactura",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deletePagoFactura(
    @common.Param() params: PagoFacturaWhereUniqueInput
  ): Promise<PagoFactura | null> {
    try {
      return await this.service.deletePagoFactura({
        where: params,
        select: {
          createdAt: true,
          fechaVencimiento: true,
          folioFactura: true,
          id: true,
          montoFactura: true,
          montoPagado: true,
          nombreProveedor: true,
          notificacionVencida: true,
          pagado: true,
          runProveedor: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
