/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ArqueoService } from "../arqueo.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ArqueoCreateInput } from "./ArqueoCreateInput";
import { Arqueo } from "./Arqueo";
import { ArqueoFindManyArgs } from "./ArqueoFindManyArgs";
import { ArqueoWhereUniqueInput } from "./ArqueoWhereUniqueInput";
import { ArqueoUpdateInput } from "./ArqueoUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ArqueoControllerBase {
  constructor(
    protected readonly service: ArqueoService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Arqueo })
  @nestAccessControl.UseRoles({
    resource: "Arqueo",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createArqueo(@common.Body() data: ArqueoCreateInput): Promise<Arqueo> {
    return await this.service.createArqueo({
      data: data,
      select: {
        cajera: true,
        createdAt: true,
        fechaArqueo: true,
        id: true,
        monto: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Arqueo] })
  @ApiNestedQuery(ArqueoFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Arqueo",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async arqueos(@common.Req() request: Request): Promise<Arqueo[]> {
    const args = plainToClass(ArqueoFindManyArgs, request.query);
    return this.service.arqueos({
      ...args,
      select: {
        cajera: true,
        createdAt: true,
        fechaArqueo: true,
        id: true,
        monto: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Arqueo })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Arqueo",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async arqueo(
    @common.Param() params: ArqueoWhereUniqueInput
  ): Promise<Arqueo | null> {
    const result = await this.service.arqueo({
      where: params,
      select: {
        cajera: true,
        createdAt: true,
        fechaArqueo: true,
        id: true,
        monto: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Arqueo })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Arqueo",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateArqueo(
    @common.Param() params: ArqueoWhereUniqueInput,
    @common.Body() data: ArqueoUpdateInput
  ): Promise<Arqueo | null> {
    try {
      return await this.service.updateArqueo({
        where: params,
        data: data,
        select: {
          cajera: true,
          createdAt: true,
          fechaArqueo: true,
          id: true,
          monto: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Arqueo })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Arqueo",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteArqueo(
    @common.Param() params: ArqueoWhereUniqueInput
  ): Promise<Arqueo | null> {
    try {
      return await this.service.deleteArqueo({
        where: params,
        select: {
          cajera: true,
          createdAt: true,
          fechaArqueo: true,
          id: true,
          monto: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
